# Generated by Django 4.2 on 2024-07-08 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth_org', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='userId',
        ),
    ]
